version: "3"
services:
  sync:
    build:
      context: .
      dockerfile: apt-repo.Dockerfile
    environment:
      TZ: $TZ
    volumes:
      - ./cache:/var/spool/apt-mirror/skel
      - $NFS_DIR:/var/spool/apt-mirror/mirror
    deploy:
      resources:
        limits:
          memory: 4g
  www:
    build:
      context: .
      dockerfile: www.Dockerfile
    environment:
      TZ: $TZ
    volumes:
      - ./app/support_scripts:/usr/share/nginx/html/_support_scripts:ro
      - $NFS_DIR/us.archive.ubuntu.com/ubuntu:/usr/share/nginx/html/ubuntu:ro
      - $NFS_DIR/download.docker.com/linux/ubuntu:/usr/share/nginx/html/docker:ro
    restart: unless-stopped
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:80
    deploy:
      resources:
        limits:
          memory: 4g