version: "3"
services:
  apt-mirror:
    build:
      context: .
      dockerfile: apt-repo.Dockerfile
    environment:
      TZ: US/Hawaii
    volumes:
      - ./app/apt-mirror/mirror.list:/etc/apt/mirror.list:ro
      - $NFS_DIR:/var/spool/apt-mirror/mirror
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - apt-mirror
  apt-www:
    build:
      context: .
      dockerfile: www.Dockerfile
    environment:
      TZ: US/Hawaii
    volumes:
      - ./app/support_scripts:/usr/share/nginx/html/_support_scripts:ro
      - $NFS_DIR:/usr/share/nginx/html/mirrors:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - proxy_gateway
networks:
  apt-mirror:
    name: apt-mirror
  proxy_gateway:
    name: proxy_gateway
    external: true