filebeat.modules:
- module: netflow
  log:
    enabled: true
    var:
      netflow_host: 0.0.0.0
      netflow_port: 2055

setup.template:
  name: "netflow"
  pattern: "netflow-cisco-og.networks"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]  
  index: "netflow-cisco-og.networks"