---
services:
  rproxy:
    command: ["-g", "daemon off;"]
    # inject additional commands here if needed
    # http://nginx.org/en/docs/switches.html
    environment:
      TZ: US/Hawaii
    hostname: rproxy
    build:
      context: .
    ports:
      - 10.0.20.30:80:80
      - 10.0.20.30:443:443
    volumes:
      #- ./secrets/certs:/etc/letsencrypt:ro
      - ../prod_letsencrypt/secrets/certs:/etc/letsencrypt:ro
      - ./logs:/var/log/nginx/
    restart: unless-stopped
