---
services:
  rproxy:
    command: ["-g", "daemon off;"]
    # inject additional commands here if needed
    # http://nginx.org/en/docs/switches.html
    environment:
      TZ: US/Hawaii
    hostname: rproxy
    build:
      context: .
    ports:
      - 10.0.20.30:80:80
      - 10.0.20.30:443:443
    volumes:
      - ./secrets/certs:/etc/letsencrypt:ro
      - ./logs:/var/log/nginx/
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g
  letsencrypt:
    image: certbot/certbot
    ports:
      - 10.0.20.30:80:80
      - 10.0.20.30:443:443
    volumes:
      - ./secrets/certs:/etc/letsencrypt
    deploy:
      resources:
        limits:
          memory: 8g
    command: [
      "-vn",
      "certonly",
      "--key-type=ecdsa",
      "--elliptic-curve", "secp256r1",
      "--standalone",
      "--agree-tos",
      "--debug-challenges",
      "-m", "nrogrydziak@gmail.com",
      "--cert-name", "ogrydziak.net-ecdsa",
      "-d", "ogrydziak.net,www.ogrydziak.net",
      "-d", "ogrydziak.com,www.ogrydziak.com",
      "-d", "ogrydziak.org,www.ogrydziak.org",
      "-d", "ogrydziak.ninja,www.ogrydziak.ninja",
      "-d", "authentik.ogrydziak.net",
      "-d", "code.ogrydziak.net",
      "-d", "download.ogrydziak.net",
      "-d", "eve.ogrydziak.net",
      "-d", "files.ogrydziak.net",
      "-d", "guac.ogrydziak.net",
      "-d", "kibana.ogrydziak.net",
      "-d", "meet.ogrydziak.net",
      "-d", "mirror.ogrydziak.net",
      "-d", "nessus.ogrydziak.net",
      "-d", "netbox.ogrydziak.net",
      "-d", "opnsense.ogrydziak.net",
      "-d", "plex.ogrydziak.net,plexstats.ogrydziak.net",
      "-d", "portainer.ogrydziak.net",
      "-d", "pve.ogrydziak.net",
      "-d", "unifi.ogrydziak.net",
      "-d", "zabbix.ogrydziak.net"
      #"--dry-run"
    ]