---
cisco_routers:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: ansible
    ansible_ssh_private_key_file: ./secrets/ansible_ecdsa256.key
    LOGGING_INTERFACE: GigabitEthernet1
    LOGGING_IP: 10.0.20.30
    NTP_INTERFACE: GigabitEthernet1
    NTP_SRV_CSR: 10.0.20.30
  hosts:
    og_net-csr1000-eveng:
      ansible_host: 10.0.20.105
