version: "3.9"
networks:
  swag:
    ipam:
      config:
        - subnet: $SWAG_NETWORK
  servers:
    ipam:
      config:
        - subnet: $SERVERS_NETWORK
  servers_vlan:
    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
      driver: default
      config:
        - subnet: 10.0.20.0/24
          gateway: 10.0.20.1
