---
version: "3"
services:
  netbox:
    depends_on:
      - redis
      - postgres
    image: lscr.io/linuxserver/netbox:latest
      #https://hub.docker.com/r/linuxserver/netbox
    environment:
      TZ: US/Hawaii
      PUID: 1000
      PGID: 1000
      ALLOWED_HOST: netbox.ogrydziak.net
      FILE__SUPERUSER_EMAIL: /run/secrets/superuser_email
      FILE__SUPERUSER_PASSWORD: /run/secrets/superuser_password
      FILE__DB_USER: /run/secrets/db_user
      FILE__DB_PASSWORD: /run/secrets/db_password
      
      # Enable python-social-auth
      REMOTE_AUTH_ENABLED: 'True'
      REMOTE_AUTH_BACKEND: 'social_core.backends.open_id_connect.OpenIdConnectAuth'

      # python-social-auth config
      SOCIAL_AUTH_OIDC_ENDPOINT: https://authentik.ogrydziak.net/application/o/netbox/
      FILE__SOCIAL_AUTH_OIDC_KEY: /run/secrets/social_auth_oidc_key
      FILE__SOCIAL_AUTH_OIDC_SECRET: /run/secrets/social_auth_oidc_secret
      LOGOUT_REDIRECT_URL: https://authentik.ogrydziak.net/application/o/netbox/end-session/

      #- REMOTE_AUTH_HEADER:
      REMOTE_AUTH_AUTO_CREATE_USER: 'True'
      #- REMOTE_AUTH_DEFAULT_GROUPS: 
      #- REMOTE_AUTH_DEFAULT_PERMISSIONS:
    env_file:
      - ./secrets/auth.env
      #https://docs.goauthentik.io/integrations/services/netbox/
    volumes:
      - ./data/netbox:/config
    #restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    secrets:
      - superuser_email
      - superuser_password
      - db_user
      - db_password
      - socaial_auth_oidc_endpoint
      #- redis_password
    networks:
      - proxy_gateway
      - netbox
  postgres:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    networks:
      - netbox
    deploy:
      resources:
        limits:
          memory: 4g
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    networks:
      - netbox
    deploy:
      resources:
        limits:
          memory: 4g
  redis-caching:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data/redis-caching:/data
    networks:
      - netbox
    deploy:
      resources:
        limits:
          memory: 4g
secrets:
  superuser_email:
    file: ./secrets/superuser_email.txt
  superuser_password:
    file: ./secrets/superuser_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  social_auth_oidc_key:
    file: ./secrets/social_auth_oidc_key.txt
  social_auth_oidc_secret:
    file: ./secrets/social_auth_oidc_secret.txt
networks:
  netbox:
    name: netbox
  proxy_gateway:
    name: proxy_gateway
    external: true