---
version: "3"
services:
  netbox:
    depends_on:
      - redis
      - postgres
    image: lscr.io/linuxserver/netbox:latest
      #https://hub.docker.com/r/linuxserver/netbox
    environment:
      TZ: US/Hawaii
      PUID: $PUID
      PGID: $PGID
      ALLOWED_HOST: netbox.ogrydziak.net
      #FILE__SUPERUSER_EMAIL: /run/secrets/superuser_email
      #FILE__SUPERUSER_PASSWORD: /run/secrets/superuser_password
      FILE__DB_USER: /run/secrets/db_user
      FILE__DB_PASSWORD: /run/secrets/db_password
      REMOTE_AUTH_ENABLED: 'True'
      REMOTE_AUTH_BACKEND: 'social_core.backends.open_id_connect.OpenIdConnectAuth'
      SOCIAL_AUTH_OIDC_ENDPOINT: 'https://authentik.ogrydziak.net/application/o/netbox/'
      SOCIAL_AUTH_OIDC_KEY: '99s8UnLzKDfh1rdb4iKltUNqDBgp3QxFpYAQ7vbU'
      SOCIAL_AUTH_OIDC_SECRET: 'NfrGZWMFWppfybEgZprw9jBddLauo9wX71pwu10bKLEy571iDd0m1WAoCJ7iX06YgIFiozQZfpAbQMNqpU4frvMq39CrJMW0meXLHzyylIHMZl39rgqQIAZKFGz9PYFA'
      LOGOUT_REDIRECT_URL: 'https://authentik.ogrydziak.net/application/o/netbox/end-session/'
      #- REMOTE_AUTH_HEADER:
      REMOTE_AUTH_AUTO_CREATE_USER: 'True'
      #- REMOTE_AUTH_DEFAULT_GROUPS: 
      #- REMOTE_AUTH_DEFAULT_PERMISSIONS:
    volumes:
      - ./data/netbox:/config
    #restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    secrets:
      - superuser_email
      - superuser_password
      - db_user
      - db_password
      #- redis_password
    networks:
      - proxy_gateway
      - netbox
  postgres:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    networks:
      - netbox
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    networks:
      - netbox
  redis-caching:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./data/redis-caching:/data
    networks:
      - netbox
secrets:
  superuser_email:
    file: ./secrets/superuser_email.txt
  superuser_password:
    file: ./secrets/superuser_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
networks:
  netbox:
    name: netbox
  proxy_gateway:
    name: proxy_gateway
    external: true