services:
  code:
    image: ghcr.io/linuxserver/code-server:latest
      #https://hub.docker.com/r/linuxserver/code-server
    environment:
      TZ: US/Hawaii
      PUID: 1000
      PGID: 1000
      DEFAULT_WORKSPACE: /app
      PROXY_DOMAIN: cs.ogrydziak.net
    volumes:
      - ./data:/config
      - /disk2/docker:/app/docker
      - /nfs/gdrive:/app/gdrive
      - /home/crashdummy:/app/crashdummy
      #- /disk2/docker/prod/devbox/data:/cs/devbox
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - proxy_gateway
networks:
  proxy_gateway:
    name: proxy_gateway
    external: true