version: "3"
services:
  zabbix_db:
    #entrypoint: mysqld_safe --skip-grant-tables --user=mysql
      #get access to db if locked out
    image: docker.io/library/mariadb:10.11
      #find compatible mariadb tag in what's new manual
      #https://www.zabbix.com/documentation/current/en/manual/introduction
      #https://hub.docker.com/_/mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        #https://mariadb.com/kb/en/mariadb-docker-environment-variables/
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
    secrets:
      - db_root_password
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  zabbix_srv:
    image: zabbix/zabbix-server-mysql
      #https://hub.docker.com/r/zabbix/zabbix-server-mysql
    depends_on:
      - zabbix_db
    env_file:
      - zabbix.env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
        #https://hub.docker.com/r/zabbix/zabbix-server-mysql
    secrets:
      - db_root_password
      - db_user
      - db_password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  zabbix_agent:
    image: zabbix/zabbix-agent2
    #https://hub.docker.com/r/zabbix/zabbix-agent2
    depends_on:
      - zabbix_db
      - zabbix_srv
    user: root
      #needed to reader docker.sock
    env_file:
      - zabbix.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  zabbix_www:
    image: zabbix/zabbix-web-nginx-mysql
    #https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql
    depends_on:
      - zabbix_db
      - zabbix_srv
      - zabbix_agent
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:8080
    env_file:
      - zabbix.env
    environment:
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt