version: "3"
services:
  zabbix_db:
    #entrypoint: mysqld_safe --skip-grant-tables --user=mysql
    #get access to db if locked out
    image: docker.io/library/mariadb:10.11
    #find compatible mariadb tag in what's new manual
    #https://www.zabbix.com/documentation/current/en/manual/introduction
    env_file:
      - secrets/zabbix_db.env
      #ensure secrets has the following vars:
      #MYSQL_ROOT_PASSWORD=password
      #MYSQL_USER=zabbix
      #MYSQL_PASSWORD=password
      #https://mariadb.com/kb/en/mariadb-docker-environment-variables/
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  zabbix_srv:
    image: zabbix/zabbix-server-mysql
    depends_on:
      - zabbix_db
    env_file:
      - secrets/zabbix_db.env
      #DB_SERVER_HOST, MYSQL_USER, MYSQL_PASSWORD
      #https://www.zabbix.com/documentation/current/en/manual/installation/containers
      - zabbix.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  zabbix_www:
    image: zabbix/zabbix-web-nginx-mysql
    #https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql
    depends_on:
      - zabbix_db
      - zabbix_srv
      - zabbix_agent
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:8080
    env_file:
      - secrets/zabbix_db.env
      - zabbix.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  zabbix_agent:
    image: zabbix/zabbix-agent2
    #https://hub.docker.com/r/zabbix/zabbix-agent2
    depends_on:
      - zabbix_srv
    user: root
    env_file:
      - zabbix.env
    #environment:
      #- ZBX_DEBUGLEVEL=4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    privileged: true
    #zabbix needs permissions to docker
    #usermod -a -G docker zabbix
    #https://medium.com/geekculture/monitor-docker-containers-on-linux-server-with-zabbix-agent2-2a4e7708dbb7
    deploy:
      resources:
        limits:
          memory: 4g