---
- name: Tier 2 Switch NTP
  hosts: cisco_routers
  #hosts: switch
  tasks:
    - name: Disable NTP Control Mode
      cisco.ios.ios_config:
        lines:
          - no ntp allow mode control 3

    - name: Apply NTP Configuration
      cisco.ios.ios_ntp_global:
        config:
           logging: true
           servers:
             - server: "{{ NTP_SRV_CSR }}"
               prefer: true
           source: "{{ NTP_INTERFACE }}"
        state: replaced