---
- name: SNMP
  hosts: cisco_routers
  #hosts: all
  tasks:
    - name: SNMP Configuration
      cisco.ios.ios_config:
        lines:
          - snmp-server view ALL-ACCESS iso included
          #- snmp-server group NETENG v3 priv read ALL-ACCESS access NETENG
          #- snmp-server user neteng NETENG v3 auth sha 307307307 priv aes 128 307307307
        