---
- name: Remote Syslog
  hosts: all
  tasks:
    - name: Apply Timestamp Format
      cisco.ios.ios_service:
        config:
           timestamps:
             - msg: log
               enable: true
               timestamp: datetime
               datetime_options:
                 localtime: true
                 msec: true
                 show_timezone: true
                 year: true
        state: merged

    - name: Apply Archive Log Configuration
      cisco.ios.ios_config:
        lines:
          - hidekey
          - notify syslog
          - logging enable
        parents:
          - archive
          - log config

    - name: Log Login Events
      cisco.ios.ios_config:
        lines:
          - ip ssh logging events
          - login on-failure log
          - login on-success log

    - name: Apply Logging Configuration
      cisco.ios.ios_config:
        lines:
          - logging source-interface {{ LOGGING_INTERFACE }}
          - logging host {{  LOGGING_IP }} session-id hostname sequence-num-session
