services:
  checkmk:
    container_name: ${COMPOSE_PROJECT_NAME}_checkmk
    hostname: checkmk
    networks:
      - servers
    image: checkmk/check-mk-raw:2.1.0-latest
      #https://hub.docker.com/r/checkmk/check-mk-raw
      #https://hub.docker.com/r/checkmk/check-mk-free
    ports:
      - $SRV_SWAG_PROXY:$CHECKMK_H_PORT:5000
      - 9080:5000
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - $CHECKMK_DATA_DIR:/omd/sites
    tmpfs: /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g