services:
  code_server:
    container_name: ${COMPOSE_PROJECT_NAME}_code_server
    hostname: code_server
    networks:
      - servers
    image: ghcr.io/linuxserver/code-server:latest
      #https://hub.docker.com/r/linuxserver/code-server
    env_file:
      - env/linuxserver.env
      - env/cs.env
      - secrets/cs.env
    ports:
      - $SRV_SWAG_PROXY:8040:8443
    volumes:
       - $CS_DATA_DIR:/config
       - $ROOT_DIR:/docker
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g