services:
  code_server:
    depends_on:
      - rproxy
    container_name: ${COMPOSE_PROJECT_NAME}_code_server
    hostname: code_server
    networks:
      - servers
    image: ghcr.io/linuxserver/code-server:latest
      #https://hub.docker.com/r/linuxserver/code-server
    env_file:
      - env/linuxserver.env
      - env/cs.env
      - secrets/cs.env
    volumes:
       - $CS_DATA_DIR:/config
       - $ROOT_DIR:/cs/docker
       - $GDRIVE_DIR:/cs/gdrive
       - /home/crashdummy:/cs/crashdummy
       - $DEVBOX_DATA_DIR:/cs/devbox
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g