services:
  devbox:
    container_name: ${COMPOSE_PROJECT_NAME}_devbox
    hostname: devbox
    networks:
      - servers
    build:
      context: ./app/devbox
    ports:
      #- $SRV_IP_1:2013:22
      - 2013:22
    env_file:
      - secrets/devbox.env
      #add sercrets in env
      #- USER=testuser
      #- SSH_KEY=[public_key]
    volumes:
      - $DEVBOX_DATA_DIR:/app
    deploy:
      resources:
        limits:
          memory: 512m