services:
  endlessh:
    container_name: ${COMPOSE_PROJECT_NAME}_endlessh
    hostname: endlessh
    networks:
      - servers
    ports:
      - $SRV_IP_3:22:2222
    image: lscr.io/linuxserver/endlessh:latest
      #https://docs.linuxserver.io/images/docker-endlessh
    env_file:
      - env/linuxserver.env
      - env/endlessh.env
    volumes:
      - $ENDLESSH_DIR:/config
    deploy:
      resources:
        limits:
          memory: 1g