services:
  nagios:
    entrypoint: ["/bin/bash"]
      #comment to disable
    #depends_on:
    #  - swag
    container_name: prod_nagios
    hostname: nagios
    networks:
      - swag
    build:
      context: ./app/nagios
    environment:
      - NAGIOSADMIN=cisco
    ports:
      - $SRV_SWAG_PROXY:$NAGIOS_H_PORT:80
    volumes:
      - $NAGIOS_TMP_DIR:/app/tmp
        #for easily writing data back to host
    #restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g