services:
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    hostname: phpmyadmin
    networks:
      - servers
    ports:
      - $SRV_SWAG_PROXY:$PHPMYADMIN_H_PORT:80
    image: lscr.io/linuxserver/phpmyadmin:latest
      #https://hub.docker.com/r/linuxserver/phpmyadmin
    env_file:
      - env/linuxserver.env
      - env/phpmyadmin.env
    volumes:
      - $PHPMYADMIN_DATA_DIR:/config
    deploy:
      resources:
        limits:
          memory: 1g