services:
  plex:
  #https://tizutech.com/plex-transcoding-with-docker-nvidia-gpu/
    depends_on:
      - rproxy
    container_name: ${COMPOSE_PROJECT_NAME}_plex
    hostname: plex
    networks:
      - servers
    image: ghcr.io/linuxserver/plex:latest
      #https://hub.docker.com/r/linuxserver/plex
    env_file:
      - env/linuxserver.env
      - env/plex.env
    environment:
      - 'ADVERTISE_IP=https://plex.ogrydziak.net/,http://plex.ogrydziak.net/'
    volumes:
      - $PLEX_CONFIG_DIR:/config
      - $PLEX_MEDIA_DIR:/media
      - $RAMDISK:/transcode
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
        limits:
          memory: 56g
  plexstats:
    depends_on:
      - plex
      - rproxy
    container_name: ${COMPOSE_PROJECT_NAME}_plexstats
    hostname: plexstats
    networks:
      - servers
    image: ghcr.io/linuxserver/tautulli:latest
      #https://hub.docker.com/r/linuxserver/tautulli
    env_file:
      - env/linuxserver.env
    restart: unless-stopped
    volumes:
      - $PLEXSTATS_DATA_DIR:/config
      - $PLEX_CONFIG_DIR:/plex:ro
        #to read plex logs
    deploy:
      resources:
        limits:
          memory: 512m