services:
  plex:
  #https://tizutech.com/plex-transcoding-with-docker-nvidia-gpu/
    depends_on:
      - rproxy
    container_name: ${COMPOSE_PROJECT_NAME}_plex
    hostname: plex
    network_mode: host
    #networks:
      #- servers
    #ports:
      #- $SRV_SWAG_PROXY:$PLEX_H_PORT:32400
    #devices:
      #- $GPU_DEV:$GPU_DEV
    image: ghcr.io/linuxserver/plex:latest
      #https://hub.docker.com/r/linuxserver/plex
    env_file:
      - env/linuxserver.env
      - env/plex.env
    volumes:
      - $PLEX_CONFIG_DIR:/config
      - $PLEX_MEDIA_DIR:/media
      - $RAMDISK:/transcode
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
        limits:
          memory: 56g
  plexstats:
    container_name: ${COMPOSE_PROJECT_NAME}_plexstats
    hostname: plexstats
    networks:
      - servers
    image: ghcr.io/linuxserver/tautulli:latest
      #https://hub.docker.com/r/linuxserver/tautulli
    env_file:
      - env/linuxserver.env
    ports:
      - $SRV_SWAG_PROXY:$PLEXSTATS_H_PORT:8181
    restart: unless-stopped
    volumes:
      - $PLEXSTATS_DATA_DIR:/config
      - $PLEX_CONFIG_DIR:/plex:ro
        #to read plex logs
    deploy:
      resources:
        limits:
          memory: 512m