services:
  plex:
    depends_on:
      - swag
    container_name: ${COMPOSE_PROJECT_NAME}_plex
    hostname: plex
    networks:
      - plex
    devices:
      - $GPU_DEV:$GPU_DEV
    image: ghcr.io/linuxserver/plex:latest
      #https://hub.docker.com/r/linuxserver/plex
    networks:
      - servers
      - swag
    #env_file:
    #  - services/plex.env
    environment:
      - VERSION=docker
      - TZ=$TZ
      - PUID=$ID
      - PGID=$ID
    ports:
      - $SRV_SWAG_PROXY:$PLEX_H_PORT:32400
    volumes:
      - $PLEX_CONFIG_DIR:/config
      - $PLEX_MEDIA_DIR:/media
      - $RAMDISK:/transcode
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16g
  plexstats:
    depends_on:
      - plex
      - swag
    container_name: ${COMPOSE_PROJECT_NAME}_plexstats
    hostname: plexstats
    networks:
      - servers
      - swag
    image: ghcr.io/linuxserver/tautulli:latest
      #https://hub.docker.com/r/linuxserver/tautulli
    #env_file:
    #  - services/plex.env
    environment:
      - TZ=$TZ
      - PUID=$ID
      - PGID=$ID
    ports:
      - $SRV_SWAG_PROXY:$PLEXSTATS_H_PORT:8181
    restart: unless-stopped
    volumes:
      - $PLEXSTATS_CONFIG_DIR:/config
      - $PLEX_CONFIG_DIR:/plex:ro
        #to read plex logs
    deploy:
      resources:
        limits:
          memory: 512m