services:
  portainer:
    depends_on:
      - rproxy
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    hostname: portainer
    networks:
      - servers
    image: portainer/portainer-ce
      #https://hub.docker.com/r/portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PORTAINER_DATA_DIR:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g