services:
  radius_db:
    entrypoint: ["/bin/bash"]
      #comment to disable
    container_name: prod_radius_db
    hostname: radius_db
    networks:
      - servers
    build:
      context: ./app/freeradius/radius_db
    environment:
      MYSQL_ROOT_PASSWORD: $RADIUS_SQL_ROOT_PW
      #change this before deployment
      #also change default pws in
        #./app/radius_db/docker-entrypoint-initdb.d/01_create_db_add_user.sql
        #./app/daloradius/daloradius.conf.php
    volumes:
      - $RADIUS_DB_DIR:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
  radius_srv:
    entrypoint: ["/bin/bash"]
      #comment to disable
    depends_on:
      - radius_db
    container_name: prod_radius_srv
    hostname: radius_srv
    networks:
      - servers
    build:
      context: ./app/freeradius/radius_srv
    ports:
      - $SRV_IP_1:1812-1813:1812-1813/udp
    volumes:
      - $RAD_LOG_DIR:/var/log/freeradius
    #command: ["freeradius", "-X"]
    #use to troubleshoot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
  daloradius:
    entrypoint: ["/bin/bash"]
      #comment to disable
    depends_on:
      - radius_db
    container_name: prod_daloradius
    hostname: daloradius
    networks:
      - servers
      - swag
    build:
      context: ./app/freeradius/daloradius
    ports:
      - $SRV_SWAG_PROXY:$DALORADIUS_H_PORT:80
    volumes:
      - $RAD_LOG_DIR:/var/log/freeradius:ro
      #chmod +r /disk2/freeradius_srv/radius.log
      #run on host machine
      #may be necessary to ensure daloradius container has read rights to log file
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
  radius_proxy:
    entrypoint: ["/bin/bash"]
    depends_on:
      - radius_srv
    container_name: prod_radius_proxy
    hostname: radius_proxy
    networks:
      - servers
      - swag
    build:
      context: ./app/freeradius/proxy 
    shm_size: "2gb"
    restart: unless-stopped