services:
  rproxy:
    container_name: ${COMPOSE_PROJECT_NAME}_rproxy
    hostname: rproxy
    networks:
      - servers
    build:
      context: ./app/rproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $CERTBOT_DATA_DIR_ETC:/etc/letsencrypt:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g