services:
  rproxy:
    entrypoint: ["/bin/bash"]
      #comment to disable
    container_name: ${COMPOSE_PROJECT_NAME}_rproxy
    hostname: rproxy
    networks:
      - servers
    build:
      context: ./app/rproxy
    ports:
      - 9090:80
    shm_size: "2gb"
    restart: unless-stopped