services:
  steamcmd_unturned:
    container_name: ${COMPOSE_PROJECT_NAME}_unturned_pull
    networks:
      - servers
    image: steamcmd/steamcmd:ubuntu-22
    volumes:
      - $STEAMCMD_DATA_DIR/unturned:/app
    command: [
      "+force_install_dir", "/app",
      "+login", "anonymous",
      "+app_update", "1110390",
      "+quit"
    ]
  unturned_srv:
    container_name: ${COMPOSE_PROJECT_NAME}_unturned_srv
    networks:
      - servers
    build:
      context: ./app/unturned
    volumes:
      - $STEAMCMD_DATA_DIR/unturned:/app
    ports:
      - $SRV_IP_3:27015-27016:27015-27016/udp
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        limits:
          memory: 32g
    entrypoint: [
      "screen",
      "./ServerHelper.sh",
      "+secureserver/human",
    ]