services:
  swag:
    container_name: ${COMPOSE_PROJECT_NAME}_swag
    hostname: swag
    networks:
      - swag
    image: ghcr.io/linuxserver/swag:latest
      #https://hub.docker.com/r/linuxserver/swag
    environment:
      - TZ=$TZ
      - PUID=$ID
      - PGID=$ID
      - URL=$SWAG_URL
      - SUBDOMAINS=$SWAG_SUBDOMAINS
      - VALIDATION=http
      - EMAIL=$EMAIL
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=$SWAG_EXTRA_DOMAINS
      - STAGING=false
    ports:
      - $SRV_IP_1:80:80
      - $SRV_IPV6_1:80:80
      - $SRV_IPV6_WAN:80:80
      - $SRV_IP_1:443:443
      - $SRV_IPV6_1:443:443
      - $SRV_IPV6_WAN:443:443
    volumes:
      - $SWAG_CONFIG_DIR:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g