services:
  swag:
    container_name: ${COMPOSE_PROJECT_NAME}_swag
    hostname: swag
    networks:
      - swag
    image: ghcr.io/linuxserver/swag:latest
      #https://hub.docker.com/r/linuxserver/swag
    env_file:
      - env/linuxserver.env
      - env/swag.env
      - secrets/swag.env
    ports:
      - $SRV_IP_1:80:80
      - $SRV_IPV6_1:80:80
      - $SRV_IPV6_WAN:80:80
      - $SRV_IP_1:443:443
      - $SRV_IPV6_1:443:443
      - $SRV_IPV6_WAN:443:443
    volumes:
      - $SWAG_CONFIG_DIR:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g