services:
  www:
    depends_on:
      - swag
    container_name: ${COMPOSE_PROJECT_NAME}_www
    hostname: www
    networks:
      - swag
    build:
      context: ./app/www
    ports:
      - $SRV_SWAG_PROXY:$WWW_H_PORT:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m