services:
  zabbix_db:
    container_name: test_zabbix_db
    hostname: zabbix_db
    networks:
      - servers
    image: docker.io/library/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: $ZABBIX_SQL_ROOT_PW
    volumes:
      - $ZABBIX_DB_DIR:/var/lib/mysql
  zabbix_srv:
    container_name: test_zabbix_srv
    hostname: zabbix_srv
    image: zabbix/zabbix-server-mysql
    depends_on:
      - zabbix_db
    networks:
      - servers
    environment:
      - DB_SERVER_HOST=zabbix_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=$ZABBIX_SQL_ROOT_PW
  zabbix_www:
    container_name: test_zabbix_www
    hostname: zabbix_www
    image: zabbix/zabbix-web-nginx-mysql
    #https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql
    depends_on:
      - zabbix_db
      - zabbix_srv
    networks:
      - servers
    ports:
      - $SRV_IP_1:80:8080
    environment:
      - DB_SERVER_HOST=zabbix_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=$ZABBIX_SQL_ROOT_PW
      - ZBX_SERVER_HOST=zabbix_srv
      - PHP_TZ=$TZ
      - ZBX_SERVER_NAME=OG-TEST-SERVER
  zabbix_agent:
    container_name: test_zabbix_agent
    hostname: zabbix_agent
    image: zabbix/zabbix-agent
    #https://hub.docker.com/r/zabbix/zabbix-agent2
    depends_on:
      - zabbix_db
      - zabbix_srv
    networks:
      - servers
    environment:
      - ZBX_SERVER_HOST=zabbix_srv
      #- ZBX_DEBUGLEVEL=4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    privileged: "true"
    #zabbitx needs permissions to docker
    #usermod -a -G docker zabbix
    #https://medium.com/geekculture/monitor-docker-containers-on-linux-server-with-zabbix-agent2-2a4e7708dbb7