---
- name: Add Ansible User & Public Key
  hosts: cisco_routers
  tasks:
    - name: Add Ansible User
      cisco.ios.ios_user:
        name: ansible
        privilege: 15
        sshkey: "{{ lookup('file', '/app/keys/ansible_ecdsa256.pub') }}"
        state: present

    #- name: "Add Ansible User"
    #  cisco.ios.ios_config:
    #    lines: username ansible privilege 15
    #- name: "Add Public Key"
    #  cisco.ios.ios_config:
    #    lines: key-hash ecdsa-sha2-nistp256 F0DDF6ED3BE509B2400D4C35AE8E27DC crashdummy@phantom
    #    parents:
    #      - ip ssh pubkey-chain
    #      - username ansible