---
- name: Cisco Baseline
  hosts: cisco_routers
  tasks:
    - name: Configure hostname
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ inventory_hostname }}"

    - name: Set Login Banner
      cisco.ios.ios_banner:
        banner: motd
        #text: banner login test!
        text: "{{ lookup('file', '/app/banner/dod.txt') }}"
    
    - name: Remove All Except Authorized Users
      cisco.ios.ios_user:
        aggregate:
          - name: ansible
          - name: guac
          - name: cisco
        purge: true

    - name: Disable NTP Control Mode
      cisco.ios.ios_config:
        lines:
          - no ntp allow mode control 3

    - name: Apply NTP Configuration
      cisco.ios.ios_ntp_global:
        config:
           logging: true
           panic_update: true
           servers:
             - server: 10.0.20.1
               prefer: true
           source: GigabitEthernet1
        state: replaced