version: "3"
services:
  www:
    build:
      context: .
    restart: unless-stopped
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:80
    deploy:
      resources:
        limits:
          memory: 4g