filebeat.modules:
#- module: nginx
#  access:
#    enabled: true
#    var.paths: ["/logs/access.log"]
- type: syslog
  format: rfc3164
  protocol.udp:
    host: "0.0.0.0:514"
  fields: {server: "OG Networks", service: "cisco-syslog"}

output.logstash:
  hosts: ["logstash:515"]

#setup.template:
#  name: "rproxy"
#  pattern: "syslog-nginx-rproxy}"

#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]  
#  index: "syslog-nginx-rproxy"