---
snn:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: ansible
    ansible_ssh_private_key_file: ./secrets/ansible_ecdsa256.key
  children:
    xt2r:
      vars:
        LOGGING_IP: 10.0.20.30
        LOGGING_INTERFACE: Loopback0
        NTP_INTERFACE: Loopback10
      hosts:
        646020-xt2r:
          ansible_host: 10.0.20.105
    xt2s:
      vars:
        LOGGING_IP: 10.0.20.30
        LOGGING_INTERFACE: Vlan222
        NTP_INTERFACE: Vlan222
        NTP_SRV_CSR: 0.0.0.0
      hosts:
        646020-xt2s1:
          ansible_host: 10.0.20.105
    nt2s:
      vars:
        LOGGING_IP: 155.28.42.21
        LOGGING_INTERFACE: Vlan222
        NTP_INTERFACE: Vlan222
        NTP_SRV_CSR: 0.0.0.0
      hosts:
        646020-nt2s1:
          ansible_host: 10.0.20.105
        646020-nt2s2:
          ansible_host: 10.0.20.105