version: "3.9"
services:
  tftpd:
    command: [
      "--listen",
      "--secure",
      "--create",
      "--verbose",
      "--user", "tftp",
      "--blocksize", "1468",
      "--address", "${SRV_IP}:69",
      "/srv/tftp"
      #https://manpages.debian.org/testing/tftpd-hpa/tftpd.8.en.html
      #for max transfer speeds on cisco router, ensure devices can match blocksize
        #ip tftp blocksize 1468
        #ip tftp source-interface [interface]
      #default blocksize on 3850 for example is 512
      #don't be that guy
      #https://www.cisco.com/c/en/us/support/docs/wireless/5760-wireless-lan-controller/117636-technote-tftpfile-00.html
    ]
    network_mode: host
      #unclear why network mode must be host
      #bridge network results in file creation but with no data written
    build:
      context: .
    environment:
      TZ: US/Hawaii
    volumes:
      - ./data:/srv/tftp
      - ./logs:/var/log
    deploy:
      resources:
        limits:
          memory: 2g