---
services:
  letsencrypt_http:
  # use dns version if possible for wildcard cert
  # wild card crt not possible with http
  # http validation means your proxy cant also be running bound to same
  #   web port while certbot is running
    image: certbot/certbot
    ports:
      - 10.0.20.30:80:80
      - 10.0.20.30:443:443
    volumes:
      - ./secrets/certs:/etc/letsencrypt
    command: [
      "-vn",
      "certonly",
      "--key-type=ecdsa",
      "--elliptic-curve", "secp256r1",
      "--standalone",
      "--agree-tos",
      "--debug-challenges",
      "-m", "nrogrydziak@gmail.com",
      "--cert-name", "ogrydziak.net-ecdsa",
      "-d", "ogrydziak.net,www.ogrydziak.net",
      "-d", "ogrydziak.com,www.ogrydziak.com",
      "-d", "ogrydziak.org,www.ogrydziak.org",
      "-d", "ogrydziak.ninja,www.ogrydziak.ninja",
      "-d", "authentik.ogrydziak.net",
      "-d", "code.ogrydziak.net",
      "-d", "download.ogrydziak.net",
      "-d", "eve.ogrydziak.net",
      "-d", "files.ogrydziak.net",
      "-d", "guac.ogrydziak.net",
      "-d", "kibana.ogrydziak.net",
      "-d", "meet.ogrydziak.net",
      "-d", "mirror.ogrydziak.net",
      "-d", "nessus.ogrydziak.net",
      "-d", "netbox.ogrydziak.net",
      "-d", "opnsense.ogrydziak.net",
      "-d", "plex.ogrydziak.net,plexstats.ogrydziak.net",
      "-d", "portainer.ogrydziak.net",
      "-d", "pve.ogrydziak.net",
      "-d", "unifi.ogrydziak.net",
      "-d", "zabbix.ogrydziak.net"
      #"--dry-run"
    ]
  letsencrypt_dns:
    image: certbot/dns-cloudflare
    volumes:
      - ./secrets/certs:/etc/letsencrypt
    command: [
      "-vn",
      "certonly",
      "--dns-cloudflare",
      "--dns-cloudflare-credentials", "/etc/letsencrypt/cloudflare.key",
      "--preferred-challenges", "dns-01",
      "--key-type=ecdsa",
      "--elliptic-curve", "secp256r1",
      "--debug-challenges",
      "--cert-name", "ogrydziak.net-ecdsa",
      "-d", "ogrydziak.net, *.ogrydziak.net",
      "-d", "ogrydziak.com, *.ogrydziak.com",
      "-d", "ogrydziak.org, *.ogrydziak.org",
      "-d", "ogrydziak.ninja, *.ogrydziak.ninja"
      #"--dry-run"
    ]
  renew:
    image: certbot/dns-cloudflare
    volumes:
      - ./secrets/certs:/etc/letsencrypt
    command: [
      "-vn",
      "renew",
      "--cert-name", "ogrydziak.net-ecdsa",
      "--dry-run"
    ]