---
services:
  letsencrypt_dns:
    image: certbot/dns-cloudflare
    volumes:
      - ./secrets/certs:/etc/letsencrypt
    command: [
      "-vn",
      "certonly",
      "--dns-cloudflare",
      "--dns-cloudflare-credentials", "/etc/letsencrypt/cloudflare.key",
      "--preferred-challenges", "dns-01",
      "--key-type=ecdsa",
      "--elliptic-curve", "secp256r1",
      "--debug-challenges",
      "--cert-name", "ogrydziak.net-ecdsa",
      "-d", "ogrydziak.net, *.ogrydziak.net",
      "-d", "ogrydziak.com, *.ogrydziak.com",
      "-d", "ogrydziak.org, *.ogrydziak.org",
      "-d", "ogrydziak.ninja, *.ogrydziak.ninja"
      #"--dry-run"
    ]
  renew:
    image: certbot/dns-cloudflare
    volumes:
      - ./secrets/certs:/etc/letsencrypt
    command: [
      "-vn",
      "renew",
      "--cert-name", "ogrydziak.net-ecdsa"
    ]
    # "--dry-run"