---
services:
  ansible:
    #command: ["ansible-inventory", "-i", "inventory.yaml", "--list"]
    #command: ["ansible", "myhosts", "-u", "cisco", "--ask-pass", "-m", "ping", "-i", "inventory.yaml"]
    command: ["bash"]
    #stdin_open: true
    #tty: true
    build:
      context: .
    environment:
      TZ: US/Hawaii
      ANSIBLE_HOST_KEY_CHECKING: False
    volumes:
      - ./app/ansible:/app
      - ./secrets:/app/secrets:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - ansible
networks:
  ansible:
    name: ansible