version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$TAG
      #https://github.com/elastic/elasticsearch
      #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms8g -Xmx8g"
        #set no more than half of allocated memory
        #https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#set-jvm-options
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    #ports:
      #- 10.0.20.30:9200:9200
    restart: unless-stopped
    deploy:
      resources:
        limits:
          #cpus: '4.0'
          memory: 16g
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:$TAG
    depends_on:
      - elasticsearch
    environment:
      SERVERNAME: kibana.ogrydziak.net
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - proxy_gateway
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:$TAG
    depends_on:
      - elasticsearch
    volumes:
      - ./data/logstash:/usr/share/logstash/data
      - ./app/logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          #cpus: '4.0'
          memory: 8g
    networks:
      - elk
  fb_cisco_syslog:
    image: docker.elastic.co/beats/filebeat:$TAG
    depends_on:
      - logstash
    volumes:
      - ./data/filebeat/cisco_syslog:/usr/share/filebeat/data
      - ./app/filebeat/cisco_syslog.yml:/usr/share/filebeat/filebeat.yml:ro
    ports:
        - 10.0.20.30:514:514/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - elk
  fb_cisco_netflow:
    image: docker.elastic.co/beats/filebeat:$TAG
    depends_on:
      - logstash
    volumes:
      - ./data/filebeat/netflow:/usr/share/filebeat/data
      - ./app/filebeat/netflow.yml:/usr/share/filebeat/filebeat.yml:ro
    ports:
        - 10.0.20.30:2055:2055/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - elk
  fb_endlessh:
    image: docker.elastic.co/beats/filebeat:$TAG
    depends_on:
      - logstash
    volumes:
      - ./data/filebeat/endlessh:/usr/share/filebeat/data
      - ./app/filebeat/endlessh.yml:/usr/share/filebeat/filebeat.yml:ro
      - /disk2/docker/prod/endlessh/data/logs/endlessh:/logs:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - elk
  fb_bind9:
    image: docker.elastic.co/beats/filebeat:$TAG
    depends_on:
      - logstash
    volumes:
      - ./data/filebeat/bind9:/usr/share/filebeat/data
      - ./app/filebeat/bind9.yml:/usr/share/filebeat/filebeat.yml:ro
      - /disk2/docker/prod/bind9/log:/logs:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - elk
  fb_rproxy:
    image: docker.elastic.co/beats/filebeat:$TAG
    depends_on:
      - logstash
    volumes:
      - ./data/filebeat/rproxy:/usr/share/filebeat/data
      - ./app/filebeat/rproxy.yml:/usr/share/filebeat/filebeat.yml:ro
      - /disk2/docker/prod/proxy/logs:/logs:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - elk
networks:
  elk:
    name: elk
  proxy_gateway:
    name: proxy_gateway
    external: true