---
services:
  guacd:
    image: guacamole/guacd:$GUAC_TAG
      #https://hub.docker.com/r/guacamole/guacd
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - guacamole
  db:
    image: mariadb:$MARIA_TAG
      #cant find compatibility matrix but 11.3 works for guac 1.5.5
      #https://hub.docker.com/_/mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
        #https://mariadb.com/kb/en/mariadb-docker-environment-variables/
      MYSQL_DATABASE: guac
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
    secrets:
      - db_root_password
      - db_user
      - db_password
    volumes:
      - ./app:/docker-entrypoint-initdb.d:ro
          #get init.sql script from container itself
          #docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
          #https://guacamole.apache.org/doc/gug/guacamole-docker.html
      - ./data:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - guacamole
  guac:
    depends_on:
      - guacd
      - db
    image: guacamole/guacamole:$GUAC_TAG
      #https://hub.docker.com/r/guacamole/guacamole
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: guac
      MYSQL_HOSTNAME: db
      MYSQL_AUTO_CREATE_ACCOUNTS: true
        #important for oauth accounts
      OPENID_AUTHORIZATION_ENDPOINT: https://authentik.ogrydziak.net/application/o/authorize/
      OPENID_CLIENT_ID: ldp9rawpQAHpmo2hMJfhP6kkOFec57IjTy89lE5q
      OPENID_ISSUER: https://authentik.ogrydziak.net/application/o/guacamole/
      OPENID_JWKS_ENDPOINT: https://authentik.ogrydziak.net/application/o/guacamole/jwks/
      OPENID_REDIRECT_URI: https://guac.ogrydziak.net/guacamole/
        # This must match the redirect URI above
    secrets:
      - db_user
      - db_password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - guacamole
      - proxy_gateway
secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
networks:
  guacamole:
    name: guacamole
  proxy_gateway:
    name: proxy_gateway
    external: true