services:
  guacd:
    image: guacamole/guacd
      #https://hub.docker.com/r/guacamole/guacd
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  guac_db:
    image: mariadb:10
      #cant find compatibility matrix but mariadb:11 no work on guac v1.5.2
      #https://hub.docker.com/_/mariadb
    env_file:
      - secrets/guac.env
        #inc secrets for:
          #MYSQL_ROOT_PASSWORD=password1
          #MYSQL_USER=dbadmin
          #MYSQL_PASSWORD=password1
          #MYSQL_DATABASE=dbname
        #if set and on fresh mariadb, server will create new
          #root pw, user, user pw, database
    volumes:
      - ./app:/docker-entrypoint-initdb.d:ro
        #get init.sql script from container itself
        #docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
        #https://guacamole.apache.org/doc/gug/guacamole-docker.html
      - ./data:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
  guac:
    volumes:
      - ./app:/app
    depends_on:
      - guacd
      - guac_db
    image: guacamole/guacamole:latest
      #https://hub.docker.com/r/guacamole/guacamole
    env_file:
      - secrets/guac.env
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=guac_db
      - TOTP_ENABLED=true
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g