version: "3"
services:
  files:
    build:
      context: .
    environment:
      TZ: US/Hawaii
    volumes:
      - ./data:/var/www/html:ro
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:80
    deploy:
      resources:
        limits:
          memory: 4g
    restart: unless-stopped