version: "3"
services:
  files:
    build:
      context: .
    volumes:
      - ./data:/var/www/html:ro
    restart: unless-stopped
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:80
    deploy:
      resources:
        limits:
          memory: 4g