version: "3"
services:
  portainer:
    image: portainer/portainer-ce
      #https://hub.docker.com/r/portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:9000
    deploy:
      resources:
        limits:
          memory: 4g