---
services:
  download:
    image: ghcr.io/linuxserver/qbittorrent:latest
      # https://hub.docker.com/r/linuxserver/qbittorrent
    environment:
      - TZ=US/Hawaii
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/config
      - /nfs/media/download:/downloads
    ports:
      - 172.31.255.255:5010:8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g