version: "3"
services:
  #rocket database
  #run once to initiate database
  #sudo docker exec -it prod_rocket-rocket_db-1 mongosh --eval "printjson(rs.initiate())"
  rocket_db:
    image: mongo:$MONGO_TAG
    restart: unless-stopped
    command: ["--oplogSize", "128", "--replSet", "rs0"]
    volumes:
      - ./data:/data/db
    deploy:
      resources:
        limits:
          memory: 4g
  #rocketchat webapp service
  rocket_chat:
    depends_on:
      - rocket_db
    image: rocketchat/rocket.chat:$ROCKET_TAG
      #https://github.com/RocketChat/Rocket.Chat/releases
    restart: unless-stopped
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:80
    #env_file:
      #- .secret/rocket.env
        #for initial setup to avoid setup wizard
        #- OVERWRITE_SETTING_Show_Setup_Wizard=completed
        #- ADMIN_USERNAME=root
        #- ADMIN_PASS=toor
    environment:
      - PORT=80
      - ROOT_URL=https://$ROCKET_ROOT_URL
      - MONGO_OPLOG_URL=mongodb://rocket_db:27017/local
      - MONGO_URL=mongodb://rocket_db:27017/rocketchat
    deploy:
      resources:
        limits:
          memory: 4g