version: "3"
services:
  #rocket database
  #run once to initiate database
  #sudo docker exec -it prod_rocket_db mongosh --eval "printjson(rs.initiate())"
  rocket_db:
    image: mongo:6.0
    restart: unless-stopped
    command: ["--oplogSize", "128", "--replSet", "rs0"]
    volumes:
      - ./data:/data/db
    deploy:
      resources:
        limits:
          memory: 4g
  #rocketchat webapp service
  rocket_chat:
    depends_on:
      - rocket_db
    image: rocketchat/rocket.chat:$ROCKET_TAG
      #https://github.com/RocketChat/Rocket.Chat/releases
    restart: unless-stopped
    ports:
      - $PROXY_BRIDGE:$PROXY_BRIDGE_PORT:80
    environment:
      - PORT=80
      - ROOT_URL=https://$ROCKET_ROOT_URL
      - MONGO_OPLOG_URL=mongodb://rocket_db:27017/local
      - MONGO_URL=mongodb://rocket_db:27017/rocketchat
    deploy:
      resources:
        limits:
          memory: 4g