services:
  download:
    depends_on:
      - rproxy
    container_name: ${COMPOSE_PROJECT_NAME}_download
    hostname: download
    networks:
      - servers
    env_file:
      - env/linuxserver.env
    image: ghcr.io/linuxserver/qbittorrent:latest
      #https://hub.docker.com/r/linuxserver/qbittorrent
    volumes:
      - $DOWNLOADS_DATA_DIR:/config
      - $DOWNLOADS_DIR:/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g