services:
  rdesktop:
    entrypoint: ["/bin/bash"]
      #comment to disable
    container_name: ${COMPOSE_PROJECT_NAME}_rdesktop
    hostname: rdesktop
    networks:
      - servers
    image: ghcr.io/linuxserver/rdesktop:latest
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - $RDESKTOP_CONFIG_DIR:/config
    ports:
      - $SRV_IP_1:3389:3389
    shm_size: "2gb"
    restart: unless-stopped