services:
  rproxy:
    container_name: ${COMPOSE_PROJECT_NAME}_rproxy
    hostname: rproxy
    networks:
      - servers
    build:
      context: ./app/rproxy
    ports:
      - $SRV_IP_1:80:80
      - $SRV_IP_1:443:443
      - $SRV_IP_2:80:80
      - $SRV_IP_2:443:443
      - $SRV_IP_3:80:80
      - $SRV_IP_3:443:443
      - $SRV_IP_4:80:80
      - $SRV_IP_4:443:443
    volumes:
      - $CERTBOT_DATA_DIR_ETC:/etc/letsencrypt:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g