services:
  sftp:
    container_name: ${COMPOSE_PROJECT_NAME}_sftp
    networks:
      - servers
    build:
      context: ./app/sftp
    ports:
      - $SRV_IP_2:22:22
    env_file:
      - secrets/sftp.env
      #add sercrets below in 'secrets/sftp.env'
      #DEV_USER=user
      #DEV_PW=password
    volumes:
      - $SFTP_DATA_DIR:/app/sftp
    deploy:
      resources:
        limits:
          memory: 4g