services:
  steamcmd_unturned:
    container_name: ${COMPOSE_PROJECT_NAME}_unturned_update
    networks:
      - servers
    image: steamcmd/steamcmd:ubuntu-22
    volumes:
      - $STEAMCMD_DATA_DIR/unturned:/app
    command: [
      "+force_install_dir", "/app",
      "+login", "anonymous",
      "+app_update", "1110390",
      "validate",
      "+quit"
    ]
  unturned_srv:
    container_name: ${COMPOSE_PROJECT_NAME}_unturned_srv
    networks:
      - servers
    build:
      context: ./app/steamcmd
      dockerfile: unturned.Dockerfile
    volumes:
      - $STEAMCMD_DATA_DIR/unturned:/app
    ports:
      - $SRV_IP_3:27015-27016:27015-27016/udp
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        limits:
          memory: 32g
    restart: unless-stopped
    command: ["+secureserver/human"]
  steamcmd_valheim:
    container_name: ${COMPOSE_PROJECT_NAME}_valheim_update
    networks:
      - servers
    image: steamcmd/steamcmd:ubuntu-22
    volumes:
      - $STEAMCMD_DATA_DIR/valheim:/app
    command: [
      "+force_install_dir", "/app",
      "+login", "anonymous",
      "+app_update", "896660",
      "validate",
      "+quit"
    ]
  valheim_srv:
    container_name: ${COMPOSE_PROJECT_NAME}_valheim_srv
    networks:
      - servers
    build:
      context: ./app/steamcmd
      dockerfile: valheim.Dockerfile
    volumes:
      - $STEAMCMD_DATA_DIR/valheim:/app
    ports:
      - $SRV_IP_3:2456-2458:2456-2458/udp
    deploy:
      resources:
        limits:
          memory: 32g
    restart: unless-stopped
    command: [
      "-name", "Human",
      "-world", "Human",
      "-port", "2456",
      "-password", "secret"
    ]