services:
  #init https://goteleport.com/docs/management/guides/docker/
  #docker run --rm --entrypoint=/bin/sh \
    #-v /disk2/docker/prod/app/teleport:/etc/teleport \
    # public.ecr.aws/gravitational/teleport:12 \
    # -c "teleport configure > /etc/teleport/teleport.yaml"
  teleport:
    container_name: ${COMPOSE_PROJECT_NAME}_teleport
    hostname: teleport
    networks:
      - servers
    image: public.ecr.aws/gravitational/teleport:12
    restart: unless-stopped
    ports:
      - "3080:3080"
      - "3023:3023"
      - "3025:3025"
    volumes:
      - $TELEPORT_DATA_DIR:/var/lib/teleport
      - $TELEPORT_CONFIG_DIR:/etc/teleport
      