services:
  wireguard:
    restart: unless-stopped
    entrypoint: ["/bin/bash"]
      #comment to disable
    network_mode: host
    container_name: ${COMPOSE_PROJECT_NAME}_wireguard
    #hostname: wireguard
    #networks:
    #  - swag
    image: ghcr.io/linuxserver/wireguard:latest
      #https://hub.docker.com/r/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    environment:
      - TZ=$TZ
      - PUID=$ID
      - PGID=$ID
      - SERVERURL=$WG_SERVERURL
      #- ALLOWEDIPS=0.0.0.0/0
    volumes:
      - $WG_CONFIG_DIR:/config
      - /lib/modules
    #sysctls:
    #  - net.ipv4.conf.all.src_valid_mark=1
    #  - net.ipv6.conf.all.disable_ipv6=0
    #ports:
    #  - 51820:51820/udp
    #deploy:
    #  resources:
    #    limits:
    #      memory: 4g