services:
  zabbix_db:
    #entrypoint: mysqld_safe --skip-grant-tables --user=mysql
    container_name: ${COMPOSE_PROJECT_NAME}_zabbix_db
    hostname: zabbix_db
    networks:
      - servers
    image: docker.io/library/mariadb:10.11
    env_file:
      - secrets/zabbix_db.env
      #MYSQL_PASSWORD=password
      #https://mariadb.com/kb/en/mariadb-docker-environment-variables/
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    volumes:
      - $ZABBIX_DB_DIR:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
  zabbix_srv:
    container_name: ${COMPOSE_PROJECT_NAME}_zabbix_srv
    hostname: zabbix_srv
    image: zabbix/zabbix-server-mysql
    depends_on:
      - zabbix_db
    networks:
      - servers
    env_file:
      - env/zabbix.env
      - secrets/zabbix_db.env
      - secrets/zabbix.env
      #DB_SERVER_HOST, MYSQL_USER, MYSQL_PASSWORD
      #https://www.zabbix.com/documentation/current/en/manual/installation/containers
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
  zabbix_www:
    container_name: ${COMPOSE_PROJECT_NAME}_zabbix_www
    hostname: zabbix_www
    image: zabbix/zabbix-web-nginx-mysql
    #https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql
    depends_on:
      - zabbix_srv
      - zabbix_agent
    networks:
      - servers
    ports:
      - $SRV_SWAG_PROXY:$ZABBIX_H_PORT:8080
    env_file:
      - env/zabbix.env
      - secrets/zabbix_db.env
      - secrets/zabbix.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
  zabbix_agent:
    container_name: ${COMPOSE_PROJECT_NAME}_zabbix_agent
    hostname: zabbix_agent
    image: zabbix/zabbix-agent2
    #https://hub.docker.com/r/zabbix/zabbix-agent2
    depends_on:
      - zabbix_srv
    networks:
      - servers
    user: root
    environment:
      - ZBX_HOSTNAME=zabbix_srv
      - ZBX_SERVER_HOST=zabbix_srv
      #- ZBX_DEBUGLEVEL=4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    privileged: true
    #zabbitx needs permissions to docker
    #usermod -a -G docker zabbix
    #https://medium.com/geekculture/monitor-docker-containers-on-linux-server-with-zabbix-agent2-2a4e7708dbb7
    deploy:
      resources:
        limits:
          memory: 512m