---
version: "3"
services:
  download:
    image: ghcr.io/linuxserver/qbittorrent:latest
      #https://hub.docker.com/r/linuxserver/qbittorrent
    environment:
      - TZ=US/Hawaii
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/config
      - /nfs/media/download:/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - proxy_gateway
networks:
  proxy_gateway:
    name: proxy_gateway
    external: true